apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "logging-backend.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "logging-backend.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
data:
  config.json: |
{{ .Values.configJson | nindent 4 }}

